# Generated by Django 5.0 on 2023-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_employeelogin_backend_employeelogin_backend_tl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin2',
            name='name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
