# Generated by Django 5.0 on 2023-12-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_employeelogin2_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejoining',
            name='accnum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeejoining',
            name='bankname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeejoining',
            name='extrefil1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeejoining',
            name='extrefil2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeejoining',
            name='ifse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
